version: '3.5'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: shouts-laravel-app
        ports:
            - "80:80"
        volumes:
            - ./toastmaster:/var/www/html
        networks:
            - laravel-shouts
        depends_on:
            - mysql
    mysql:
        image: 'mariadb:latest'
        container_name: shouts-laravel-db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: web
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel-shouts

networks:
    laravel-shouts:
        name: laravel-shouts
